### ISSUE TITLE
Why to use twice the number of classes at the output layer?

### ISSUE THREAD

**Issue by avijit9** [jonmun/MM-SADA-code#3]
Hi,

I was just wondering why did you use output nodes equal to the twice the number of labels (in this case 16) in each of the I3D models? Specifically, I am referring to this line : https://github.com/jonmun/MM-SADA-code/blob/master/src/models/arch.py#L13

**Comment by jonmun** [comment]
This was left-over from an old research idea that didn't work out. The extra outputs are not used.

Note that this code was not intended for production or the base for a new project.
