### ISSUE TITLE
tensorflow-version-problem

### ISSUE THREAD

**Issue by lurchycc** [jonmun/MM-SADA-code#4]
在进行debug时出现如下错误：

Exception has occurred: ModuleNotFoundError
No module named 'tensorflow.compat.v1'
  File "/home/MM-SADA-code-master/src/models/i3d.py", line 31, in <module>
    import sonnet as snt
  File "/home/MM-SADA-code-master/src/models/arch.py", line 3, in <module>
    from src.models import i3d
  File "/home/MM-SADA-code-master/src/models/model.py", line 2, in <module>
    from src.models.arch import *
  File "/home/MM-SADA-code-master/src/train/train.py", line 7, in <module>
    from src.models.model import Model
这是我的pip list和conda list
pip list
Package                Version           
---------------------- ------------------
absl-py                0.6.1             
astor                  0.7.1             
astroid                2.4.2             
certifi                2018.11.29        
cloudpickle            1.6.0             
contextlib2            0.5.5             
decorator              4.4.2             
dm-sonnet              1.27              
gast                   0.4.0             
grpcio                 1.16.1            
h5py                   2.9.0             
isort                  5.6.4             
Keras-Applications     1.0.6             
Keras-Preprocessing    1.0.5             
lazy-object-proxy      1.4.3             
Markdown               3.0.1             
mccabe                 0.6.1             
mkl-fft                1.0.6             
mkl-random             1.0.2             
numpy                  1.15.4            
pandas                 0.24.2            
pip                    18.1              
pprofile               2.0.2             
protobuf               3.6.1             
pylint                 2.6.0             
python-dateutil        2.7.5             
pytz                   2018.7            
scikit-learn           0.20.3            
scipy                  1.2.1             
semantic-version       2.6.0             
setuptools             40.6.3            
six                    1.15.0            
sklearn                0.0               
tensorboard            1.12.2            
tensorflow             1.12.0            
tensorflow-probability 0.4.0             
termcolor              1.1.0             
tfp-nightly            0.12.0.dev20201116
toml                   0.10.2            
typed-ast              1.4.1             
Werkzeug               0.14.1            
wheel                  0.32.3            
wrapt                  1.11.0 
conda list 
# packages in environment at /home/anaconda/envs/mmsada:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_tflow_select             2.1.0                       gpu  
absl-py                   0.6.1                    py36_0  
astor                     0.7.1                    py36_0  
blas                      1.0                         mkl  
bzip2                     1.0.6                h14c3975_5  
c-ares                    1.15.0               h7b6447c_1  
ca-certificates           2018.03.07                    0  
cairo                     1.14.12              h8948797_3  
certifi                   2018.11.29               py36_0  
contextlib2               0.5.5                     <pip>
cudatoolkit               9.0                  h13b8566_0  
cudnn                     7.1.2                 cuda9.0_0  
cupti                     9.0.176                       0  
dm-sonnet                 1.27                      <pip>
ffmpeg                    4.0                  hcdf2ecd_0  
fontconfig                2.13.0               h9420a91_0  
freeglut                  3.0.0                hf484d3e_5  
freetype                  2.9.1                h8a8886c_1  
gast                      0.2.0                    py36_0  
glib                      2.56.2               hd408876_0  
graphite2                 1.3.12               h23475e2_2  
grpcio                    1.16.1           py36hf8bcb03_1  
h5py                      2.8.0            py36h61e79e4_3  
h5py                      2.9.0                     <pip>
harfbuzz                  1.8.8                hffaf4a1_0  
hdf5                      1.8.20               hba1933b_1  
icu                       58.2                 h9c2bf20_1  
intel-openmp              2019.1                      144  
jasper                    2.0.14               h07fcdf6_1  
jpeg                      9b                   h024ee3a_2  
Keras-Applications        1.0.6                     <pip>
keras-applications        1.0.8                      py_1  
keras-preprocessing       1.1.0                      py_1  
Keras-Preprocessing       1.0.5                     <pip>
libedit                   3.1.20170329         h6b74fdf_2  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 8.2.0                hdf63c60_1  
libgfortran-ng            7.3.0                hdf63c60_0  
libglu                    9.0.0                hf484d3e_1  
libopencv                 3.4.2                h765d7f9_1  
libopus                   1.3                  h7b6447c_0  
libpng                    1.6.35               hbc83047_0  
libprotobuf               3.6.1                hd408876_0  
libstdcxx-ng              8.2.0                hdf63c60_1  
libtiff                   4.0.9                he85c1e1_2  
libuuid                   1.0.3                h1bed415_2  
libvpx                    1.7.0                h439df22_0  
libxcb                    1.13                 h1bed415_1  
libxml2                   2.9.8                h26e45fe_1  
markdown                  3.0.1                    py36_0  
mkl                       2019.1                      144  
mkl_fft                   1.0.6            py36hd81dba3_0  
mkl_random                1.0.2            py36hd81dba3_0  
ncurses                   6.1                  he6710b0_1  
numpy                     1.15.4           py36h7e9f1db_0  
numpy-base                1.15.4           py36hde5b4d6_0  
opencv                    3.4.2            py36h40b0b35_1  
openssl                   1.1.1a               h7b6447c_0  
pandas                    0.24.2           py36he6710b0_0  
pcre                      8.42                 h439df22_0  
pip                       18.1                     py36_0  
pixman                    0.34.0               hceecf20_3  
pprofile                  2.0.2                     <pip>
protobuf                  3.6.1            py36he6710b0_0  
py-opencv                 3.4.2            py36h765d7f9_1  
python                    3.6.8                h0371630_0  
python-dateutil           2.7.5                    py36_0  
pytz                      2018.7                   py36_0  
readline                  7.0                  h7b6447c_5  
scikit-learn              0.20.3                    <pip>
scipy                     1.2.1            py36h7c811a0_0  
semantic-version          2.6.0                     <pip>
setuptools                40.6.3                   py36_0  
six                       1.12.0                   py36_0  
sklearn                   0.0                       <pip>
sqlite                    3.26.0               h7b6447c_0  
tensorboard               1.12.2           py36he6710b0_0  
tensorflow                1.12.0          gpu_py36he68c306_0  
tensorflow-base           1.12.0          gpu_py36h8e0ae2d_0  
tensorflow-probability    0.4.0                     <pip>
termcolor                 1.1.0                    py36_1  
tk                        8.6.8                hbc83047_0  
werkzeug                  0.14.1                   py36_0  
wheel                     0.32.3                   py36_0  
wrapt                     1.11.0                    <pip>
xz                        5.2.4                h14c3975_4  
zlib                      1.2.11               h7b6447c_3  
what should I do ?

**Comment by jonmun** [comment]
Hi,

This is an issue with the installation of DeepMind's sonnet, see the github documentation for sonnet here: https://github.com/deepmind/sonnet/tree/master

The GPU pip installation of sonnet used to replicate the results (version 1.27) no longer exists. I would recommend installing TensorFlow >= 1.5 which is compatable with the more resent versions of sonnet, following the instruction on the Sonnet Github page.

I hope that helps.
